### ISSUE TITLE
benchmarks and supported rsync options

### ISSUE THREAD

**Issue by matu3ba** [dmerejkowsky/rusync#11]

**Comment by dmerejkowsky** [comment]
Not sure what you want based on the title alone - care to elaborate ?

As I said is the README, I'm pretty happy with the feature set right now and I find the performances good enough for my use cases

**Comment by matu3ba** [comment]
1. Explaining the behavior in contrast to `rsync` or simply copying the rsync definition (`rsync -r` and `rsync -rp` would be my guess, but the README and help does not elaborate).
2. Compare the two options against `rsync`.

**Comment by dmerejkowsky** [comment]
We'll there's only one command-line option, `--no-perms` and it's documented in `--help`. I'll add a line in the README
