### ISSUE TITLE
Sync with progress callback

### ISSUE THREAD

**Issue by mmstick** [dmerejkowsky/rusync#5]
I'd like to use this within [distinst](https://github.com/pop-os/distinst/) and other projects, but that requires that the API has a progress callback that can be used to display a progress bar in a UI.

**Comment by dmerejkowsky** [comment]
Thanks for the suggestion!

It was a bit tricky to implement, but I think the overall architecture is better now :)

Please take a look at the added documentation in #6 and tell me if there's something missing or badly explained.

Cheers!

**Comment by mmstick** [comment]
The documentation looks good. I'll check it out tomorrow.

**Comment by dmerejkowsky** [comment]
Well, it's been three weeks. Let's merge this and make a new release!
